language: node_js
node_js:
  - 10
jobs:
  include:
    - stage: 'Lint check'
      name: 'Lint check'
      script: npm run eslint
    - stage: 'Test'
      name: 'Unit Testing'
      script: npm run test
    - stage: 'Run typescript build'
      name: 'Run typescript build'
      script: npm run build
